// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGIpUgDTpXG1J2WhkyNDugCiEibQ1XUj4',
    appId: '1:647010686442:web:294c8c9507b46258c3ce93',
    messagingSenderId: '647010686442',
    projectId: 'soul-chat-backend',
    authDomain: 'soul-chat-backend.firebaseapp.com',
    storageBucket: 'soul-chat-backend.firebasestorage.app',
    measurementId: 'G-ZRV1EGEJ3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzJPw8cLCVPBcUq1ZGEQnOESC9wKbaEI',
    appId: '1:647010686442:android:f2c9b6d7502c55d2c3ce93',
    messagingSenderId: '647010686442',
    projectId: 'soul-chat-backend',
    storageBucket: 'soul-chat-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5YDF5gPTWy2bScxipDkcpNFSrzzfb1J0',
    appId: '1:647010686442:ios:0e41a3dddb6f0a49c3ce93',
    messagingSenderId: '647010686442',
    projectId: 'soul-chat-backend',
    storageBucket: 'soul-chat-backend.firebasestorage.app',
    iosBundleId: 'com.example.soulChat',
  );
}
